[package]
name = "passacaglia-core"
description = "Core musical abstractions (pitch, interval, scale, tuning, structure) for the passacaglia music engine."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
passacaglia-common.workspace = true
num-rational.workspace = true
num-traits.workspace = true

[lints]
workspace = true
